version: '3'

services:
  cockroachdb:
    image: cockroachdb/cockroach
    container_name: cockroachdb
    ports:
      - "26257:26257"
      - "8080:8080"
    expose:
      - "8080"
      - "26257"
    volumes:
      - ./:/var/lib/cockroach
    command: start --insecure

  db-init:
    image: cockroachdb/cockroach
    depends_on:
      - cockroachdb
    volumes:
      - ./setup_db.sh:/setup_db.sh
    entrypoint: "/bin/bash"
    command: /setup_db.sh

  app:
    container_name: scraping
    image: scraping
    ports:
      - 8005:8005
    links:
      - cockroachdb
    depends_on:
      - db-init
    environment:
      - "DB_PORT=26257"
      - "DB_HOST=cockroachdb"
      - "DB_NAME=scraping"
      - "DB_USER=scraping"
    restart: on-failure